server:
  port: 8787
  context-path: /springboot_cfigMapper
  jsp-servlet:
    init-parameters:
      developments: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 930208
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cmfz
  username: root
  password: 930208
mybatis:
  mapper-locations: com/dyq/mapper/*Mapper.xml
  type-aliases-package: com.dyq.entity